version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    environment:
      - API_URL=http://api:3000
    depends_on:
      - api

  api:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm init -y && npm install express cors && node server.js"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
